//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiotVietTimeSheet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KiotVietTimeSheet.Resources.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói nâng cao.
        /// </summary>
        public static string advance_package {
            get {
                return ResourceManager.GetString("advance_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp.
        /// </summary>
        public static string allowance {
            get {
                return ResourceManager.GetString("allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phụ cấp.
        /// </summary>
        public static string allowance_name {
            get {
                return ResourceManager.GetString("allowance_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự động.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói hỗ trợ.
        /// </summary>
        public static string basic_package {
            get {
                return ResourceManager.GetString("basic_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm việc cho chi nhánh.
        /// </summary>
        public static string branch_day {
            get {
                return ResourceManager.GetString("branch_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoa hồng.
        /// </summary>
        public static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết bảng hoa hồng.
        /// </summary>
        public static string commission_detail {
            get {
                return ResourceManager.GetString("commission_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng hoa hồng.
        /// </summary>
        public static string commission_table {
            get {
                return ResourceManager.GetString("commission_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bảng hoa hồng.
        /// </summary>
        public static string commission_tableName {
            get {
                return ResourceManager.GetString("commission_tableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm trừ.
        /// </summary>
        public static string deduction {
            get {
                return ResourceManager.GetString("deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên giảm trừ.
        /// </summary>
        public static string deduction_name {
            get {
                return ResourceManager.GetString("deduction_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string department_name {
            get {
                return ResourceManager.GetString("department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string employee_address {
            get {
                return ResourceManager.GetString("employee_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        public static string employee_CMDN {
            get {
                return ResourceManager.GetString("employee_CMDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string employee_code {
            get {
                return ResourceManager.GetString("employee_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string employee_email {
            get {
                return ResourceManager.GetString("employee_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string employee_name {
            get {
                return ResourceManager.GetString("employee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh nhân viên.
        /// </summary>
        public static string employee_picture {
            get {
                return ResourceManager.GetString("employee_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc.
        /// </summary>
        public static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chấm công.
        /// </summary>
        public static string fingerMachine {
            get {
                return ResourceManager.GetString("fingerMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên máy chấm công.
        /// </summary>
        public static string fingerMachine_name {
            get {
                return ResourceManager.GetString("fingerMachine_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial máy chấm công.
        /// </summary>
        public static string fingerMachine_serial {
            get {
                return ResourceManager.GetString("fingerMachine_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string gpsInfo_Address {
            get {
                return ResourceManager.GetString("gpsInfo-Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận huyện.
        /// </summary>
        public static string gpsInfo_District {
            get {
                return ResourceManager.GetString("gpsInfo-District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành phố.
        /// </summary>
        public static string gpsInfo_Province {
            get {
                return ResourceManager.GetString("gpsInfo-Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phạm vi.
        /// </summary>
        public static string gpsInfo_RadiusLimit {
            get {
                return ResourceManager.GetString("gpsInfo-RadiusLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường xã.
        /// </summary>
        public static string gpsInfo_WardName {
            get {
                return ResourceManager.GetString("gpsInfo-WardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lễ tết.
        /// </summary>
        public static string holiday {
            get {
                return ResourceManager.GetString("holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kỳ nghỉ.
        /// </summary>
        public static string holiday_name {
            get {
                return ResourceManager.GetString("holiday_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ nghỉ / lễ tết.
        /// </summary>
        public static string holiday_t {
            get {
                return ResourceManager.GetString("holiday_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string jobTitle {
            get {
                return ResourceManager.GetString("jobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức danh.
        /// </summary>
        public static string jobTitle_name {
            get {
                return ResourceManager.GetString("jobTitle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhân viên.
        /// </summary>
        public static string manageEmployees {
            get {
                return ResourceManager.GetString("manageEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ công.
        /// </summary>
        public static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string mobilePhone {
            get {
                return ResourceManager.GetString("mobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương.
        /// </summary>
        public static string paysheet {
            get {
                return ResourceManager.GetString("paysheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảng lương.
        /// </summary>
        public static string paysheet_code {
            get {
                return ResourceManager.GetString("paysheet_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bảng lương.
        /// </summary>
        public static string paysheet_name {
            get {
                return ResourceManager.GetString("paysheet_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu lương.
        /// </summary>
        public static string paysheet_template {
            get {
                return ResourceManager.GetString("paysheet_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại lương.
        /// </summary>
        public static string paysheet_type {
            get {
                return ResourceManager.GetString("paysheet_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu lương.
        /// </summary>
        public static string payslip {
            get {
                return ResourceManager.GetString("payslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi phạm.
        /// </summary>
        public static string penalize {
            get {
                return ResourceManager.GetString("penalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vi phạm.
        /// </summary>
        public static string penalize_name {
            get {
                return ResourceManager.GetString("penalize_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi.
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ lặp.
        /// </summary>
        public static string secondIteration {
            get {
                return ResourceManager.GetString("secondIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca.
        /// </summary>
        public static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ca.
        /// </summary>
        public static string shift_name {
            get {
                return ResourceManager.GetString("shift_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu áp dụng.
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mẫu áp dụng.
        /// </summary>
        public static string template_name {
            get {
                return ResourceManager.GetString("template_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ngày làm việc.
        /// </summary>
        public static string workingDay {
            get {
                return ResourceManager.GetString("workingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
