//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiotVietTimeSheet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KiotVietTimeSheet.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm {0} thành công.
        /// </summary>
        public static string add_successed {
            get {
                return ResourceManager.GetString("add_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới chi tiết làm việc.
        /// </summary>
        public static string addWorkSchedule {
            get {
                return ResourceManager.GetString("addWorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chỉ cho phép tối đa {1} ảnh.
        /// </summary>
        public static string allow_maximumPicture {
            get {
                return ResourceManager.GetString("allow_maximumPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số API không chính xác.
        /// </summary>
        public static string api_wrong_parameter {
            get {
                return ResourceManager.GetString("api_wrong_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tự động tạo lịch làm việc khi kết thúc: &lt;strong&gt;{0}&lt;/strong&gt;&lt;br&gt;- Ngày bắt đầu: {1} {2}&lt;br&gt;.
        /// </summary>
        public static string auditCreateShortTitle {
            get {
                return ResourceManager.GetString("auditCreateShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch làm việc cho nhân viên: &lt;strong&gt;{0}&lt;/strong&gt;.&lt;br&gt;- Tự động tạo lịch làm việc khi kết thúc: &lt;strong&gt;{1}&lt;/strong&gt;&lt;br&gt;- Ngày bắt đầu: {2} {3}&lt;br&gt;.
        /// </summary>
        public static string auditCreateTitle {
            get {
                return ResourceManager.GetString("auditCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ lịch làm việc cho nhân viên: &lt;strong&gt;{0}&lt;/strong&gt;&lt;br&gt;.
        /// </summary>
        public static string auditRejectHeadTitle {
            get {
                return ResourceManager.GetString("auditRejectHeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ngày bắt đầu: {0} {1}&lt;br&gt;.
        /// </summary>
        public static string auditRejectTitle {
            get {
                return ResourceManager.GetString("auditRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Lặp lại mỗi &lt;strong&gt;{0}&lt;/strong&gt;: &lt;strong&gt;{1}&lt;/strong&gt;&lt;br&gt;.
        /// </summary>
        public static string auditShiftRepeat {
            get {
                return ResourceManager.GetString("auditShiftRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string autoKeeping_log_detail_date {
            get {
                return ResourceManager.GetString("autoKeeping_log_detail_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in - Out.
        /// </summary>
        public static string autoKeeping_log_detail_status_2 {
            get {
                return ResourceManager.GetString("autoKeeping_log_detail_status_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string autoKeeping_log_detail_status_title {
            get {
                return ResourceManager.GetString("autoKeeping_log_detail_status_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin chi tiết làm việc: Hệ thống tự động chấm công.
        /// </summary>
        public static string autoKeeping_log_title {
            get {
                return ResourceManager.GetString("autoKeeping_log_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thể thay đổi chi nhánh..
        /// </summary>
        public static string branch_canUpdate {
            get {
                return ResourceManager.GetString("branch_canUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thể thêm mới {0}.
        /// </summary>
        public static string can_addMore {
            get {
                return ResourceManager.GetString("can_addMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ {0} thành công.
        /// </summary>
        public static string cancel_successed {
            get {
                return ResourceManager.GetString("cancel_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Thay đổi: {0}&lt;br&gt;.
        /// </summary>
        public static string changeFrom {
            get {
                return ResourceManager.GetString("changeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mã QR cho chi nhánh {0}.
        /// </summary>
        public static string changeQR {
            get {
                return ResourceManager.GetString("changeQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các chi tiết ca làm việc đã bị hủy. Vui lòng kiểm tra lại.
        /// </summary>
        public static string clocking_allClockingsDoNotExist {
            get {
                return ResourceManager.GetString("clocking_allClockingsDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các chi tiết ca làm việc đã bị hủy trước đó. Vui lòng kiểm tra lại.
        /// </summary>
        public static string clocking_allHasBeenCancelled {
            get {
                return ResourceManager.GetString("clocking_allHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi sang ca Ngừng hoạt động..
        /// </summary>
        public static string clocking_cannotChangeShiftForClockingHasShiftUnactive {
            get {
                return ResourceManager.GetString("clocking_cannotChangeShiftForClockingHasShiftUnactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi ca cho chi tiết ca làm việc đã chấm công hoặc nghỉ.
        /// </summary>
        public static string clocking_cannotChangeShiftForClockingTimekeepingOrDayOff {
            get {
                return ResourceManager.GetString("clocking_cannotChangeShiftForClockingTimekeepingOrDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chi tiết ca làm việc nào thỏa mãn điều kiện.
        /// </summary>
        public static string clocking_cannotFindClockings {
            get {
                return ResourceManager.GetString("clocking_cannotFindClockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết ca làm việc đã bị hủy..
        /// </summary>
        public static string clocking_clockingStatusIsVoid {
            get {
                return ResourceManager.GetString("clocking_clockingStatusIsVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết ca làm việc của nhân viên {0} đã bị hủy. Vui lòng kiểm tra lại.
        /// </summary>
        public static string clocking_doesNotExistEmployeeName {
            get {
                return ResourceManager.GetString("clocking_doesNotExistEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian các ca làm việc được đổi đang trùng nhau..
        /// </summary>
        public static string clocking_duplicatedTimeOfShiftChange {
            get {
                return ResourceManager.GetString("clocking_duplicatedTimeOfShiftChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã tồn tại chi tiết ca làm việc ở thời gian này. Vui lòng kiểm tra lại..
        /// </summary>
        public static string clocking_employeeHasClockingInTime {
            get {
                return ResourceManager.GetString("clocking_employeeHasClockingInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã có lịch làm việc trên ca này..
        /// </summary>
        public static string clocking_employeeHasTimeSheetInThisShift {
            get {
                return ResourceManager.GetString("clocking_employeeHasTimeSheetInThisShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chấm công không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string clocking_greaterStartTimeToday {
            get {
                return ResourceManager.GetString("clocking_greaterStartTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết ca làm việc đã bị hủy trước đó. Vui lòng kiểm tra lại.
        /// </summary>
        public static string clocking_haveBeenCancelled {
            get {
                return ResourceManager.GetString("clocking_haveBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng chi tiết ca làm việc cần cập nhật không được quá {0}..
        /// </summary>
        public static string clocking_maximumClockingUpdate {
            get {
                return ResourceManager.GetString("clocking_maximumClockingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được chấm công tối đa 100 chi tiết ca làm việc 1 lần.
        /// </summary>
        public static string clocking_maximumSelectedClocking {
            get {
                return ResourceManager.GetString("clocking_maximumSelectedClocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết ca làm việc đã bị hủy. Vui lòng kiểm tra lại.
        /// </summary>
        public static string clocking_notExist {
            get {
                return ResourceManager.GetString("clocking_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền hủy chi tiết ca làm việc trên chi nhánh {0}.
        /// </summary>
        public static string clocking_rejectError {
            get {
                return ResourceManager.GetString("clocking_rejectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên làm thay đã có lịch làm việc trong thời gian này.
        /// </summary>
        public static string clocking_replaceEmployeeOverlapTime {
            get {
                return ResourceManager.GetString("clocking_replaceEmployeeOverlapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các ca làm việc được chọn chấm công không cùng khung giờ làm..
        /// </summary>
        public static string clocking_sameShift {
            get {
                return ResourceManager.GetString("clocking_sameShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chấm công cho các chi tiết làm việc không cùng giờ làm..
        /// </summary>
        public static string clocking_sameWorkingTime {
            get {
                return ResourceManager.GetString("clocking_sameWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền cập nhật lịch làm việc trên chi nhánh {0}.
        /// </summary>
        public static string clocking_updateDragDropError {
            get {
                return ResourceManager.GetString("clocking_updateDragDropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền cập nhật chi tiết ca làm việc trên chi nhánh {0}.
        /// </summary>
        public static string clocking_updateError {
            get {
                return ResourceManager.GetString("clocking_updateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ vào phải nhỏ hơn Giờ kết thúc ca..
        /// </summary>
        public static string clockingHistory_checkedInDate {
            get {
                return ResourceManager.GetString("clockingHistory_checkedInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ ra phải lớn hơn Giờ bắt đầu ca..
        /// </summary>
        public static string clockingHistory_greaterthanOutputTimeStartTime {
            get {
                return ResourceManager.GetString("clockingHistory_greaterthanOutputTimeStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ ra không được nhỏ hơn Giờ vào.
        /// </summary>
        public static string clockingHistory_lessthanOutputTimeInputTime {
            get {
                return ResourceManager.GetString("clockingHistory_lessthanOutputTimeInputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử lịch làm việc không tồn tại trên hệ thống.
        /// </summary>
        public static string clockingHistory_notExists {
            get {
                return ResourceManager.GetString("clockingHistory_notExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập chấm công trên thiết bị di dộng.
        /// </summary>
        public static string clockingSetting {
            get {
                return ResourceManager.GetString("clockingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thêm mới bảng hoa hồng trên chi nhánh này.
        /// </summary>
        public static string commission_doNotHavePermissionToCreate {
            get {
                return ResourceManager.GetString("commission_doNotHavePermissionToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa bảng hoa hồng này.
        /// </summary>
        public static string commission_doNotHavePermissionToDelete {
            get {
                return ResourceManager.GetString("commission_doNotHavePermissionToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền cập nhật bảng hoa hồng trên chi nhánh này.
        /// </summary>
        public static string commission_doNotHavePermissionToUpdate {
            get {
                return ResourceManager.GetString("commission_doNotHavePermissionToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bảng hoa hồng đã tồn tại trên hệ thống.
        /// </summary>
        public static string commission_existsName {
            get {
                return ResourceManager.GetString("commission_existsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập Tên bảng hoa hồng.
        /// </summary>
        public static string commission_haveNotInputtedName {
            get {
                return ResourceManager.GetString("commission_haveNotInputtedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng hoa hồng chưa được chọn.
        /// </summary>
        public static string commission_haveNotSelected {
            get {
                return ResourceManager.GetString("commission_haveNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng hoa hồng {0} đã ngừng áp dụng cho chi nhánh.
        /// </summary>
        public static string commission_InActiveForBranch {
            get {
                return ResourceManager.GetString("commission_InActiveForBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện cập nhật hoa hồng.
        /// </summary>
        public static string commission_InProgress {
            get {
                return ResourceManager.GetString("commission_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoa hồng này không tồn tại.
        /// </summary>
        public static string commission_NotExist {
            get {
                return ResourceManager.GetString("commission_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm đã tồn tại trong danh sách.
        /// </summary>
        public static string commission_ProductExistInCommissionBefore {
            get {
                return ResourceManager.GetString("commission_ProductExistInCommissionBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng đã tồn tại trong {0}.
        /// </summary>
        public static string commission_ProductGroupExist {
            get {
                return ResourceManager.GetString("commission_ProductGroupExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công. Nhấn phím F5 để thấy dữ liệu mới nhất..
        /// </summary>
        public static string commissionDetail_updateToCommission {
            get {
                return ResourceManager.GetString("commissionDetail_updateToCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo {0} thành công.
        /// </summary>
        public static string create_successed {
            get {
                return ResourceManager.GetString("create_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tạo lịch cả ngày lễ tết: &lt;strong&gt;{0}&lt;/strong&gt;&lt;br&gt;.
        /// </summary>
        public static string createOnHoliday {
            get {
                return ResourceManager.GetString("createOnHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thiết bị di động.
        /// </summary>
        public static string delDeviceResult {
            get {
                return ResourceManager.GetString("delDeviceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa {0} thành công.
        /// </summary>
        public static string delete_successed {
            get {
                return ResourceManager.GetString("delete_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu lương {0} này đã xóa. Vui lòng cập nhật lại thông tin cho nhân viên..
        /// </summary>
        public static string delPayRateTemplateValidate {
            get {
                return ResourceManager.GetString("delPayRateTemplateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị di động.
        /// </summary>
        public static string deviceName {
            get {
                return ResourceManager.GetString("deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa đặt lịch làm việc cho nhân viên &lt;strong&gt;{0}&lt;/strong&gt;&lt;br&gt;.
        /// </summary>
        public static string editEmployeeClocking {
            get {
                return ResourceManager.GetString("editEmployeeClocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ngày kết thúc: {0}.
        /// </summary>
        public static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi copy dữ liệu.
        /// </summary>
        public static string error_whenCopyData {
            get {
                return ResourceManager.GetString("error_whenCopyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi tạo dữ liệu.
        /// </summary>
        public static string error_whenCreateData {
            get {
                return ResourceManager.GetString("error_whenCreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi xóa dữ liệu.
        /// </summary>
        public static string error_whenDeleteData {
            get {
                return ResourceManager.GetString("error_whenDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi lấy dữ liệu.
        /// </summary>
        public static string error_whenGetData {
            get {
                return ResourceManager.GetString("error_whenGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi khi cập nhật dữ liệu.
        /// </summary>
        public static string error_whenUpdateData {
            get {
                return ResourceManager.GetString("error_whenUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên máy chấm công.
        /// </summary>
        public static string fingerMachine_emptyName {
            get {
                return ResourceManager.GetString("fingerMachine_emptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập serial máy chấm công.
        /// </summary>
        public static string fingerMachine_emptySerial {
            get {
                return ResourceManager.GetString("fingerMachine_emptySerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả chi tiết làm việc.
        /// </summary>
        public static string forAllWork {
            get {
                return ResourceManager.GetString("forAllWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ nay trở về sau.
        /// </summary>
        public static string forCurrentTo {
            get {
                return ResourceManager.GetString("forCurrentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Xin vui lòng thử lại sau..
        /// </summary>
        public static string generalErrorMsg {
            get {
                return ResourceManager.GetString("generalErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ lễ tết đang trùng ngày với kỳ lễ tết khác..
        /// </summary>
        public static string holiday_duplicatedHoliday {
            get {
                return ResourceManager.GetString("holiday_duplicatedHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập Ngày nghỉ từ.
        /// </summary>
        public static string holiday_emptyFrom {
            get {
                return ResourceManager.GetString("holiday_emptyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập Tên kỳ lễ tết.
        /// </summary>
        public static string holiday_emptyName {
            get {
                return ResourceManager.GetString("holiday_emptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập Đến hết ngày.
        /// </summary>
        public static string holiday_emptyTo {
            get {
                return ResourceManager.GetString("holiday_emptyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu không được lớn ngày kết thúc..
        /// </summary>
        public static string holiday_fromCannotGreaterThanTo {
            get {
                return ResourceManager.GetString("holiday_fromCannotGreaterThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ lễ tết không được quá 31 ngày.
        /// </summary>
        public static string holiday_maximumDays {
            get {
                return ResourceManager.GetString("holiday_maximumDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ nghỉ lễ / tết cần cập nhật không tồn tại.
        /// </summary>
        public static string holiday_notExist {
            get {
                return ResourceManager.GetString("holiday_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến hết ngày phải lớn hơn hoặc bằng ngày nghỉ từ.
        /// </summary>
        public static string holiday_toMustGreaterOrEqualThanFrom {
            get {
                return ResourceManager.GetString("holiday_toMustGreaterOrEqualThanFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} đã bị xóa.
        /// </summary>
        public static string is_deleted {
            get {
                return ResourceManager.GetString("is_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} này đã xóa, vui lòng kiểm tra lại.
        /// </summary>
        public static string is_deletedCheckAgain {
            get {
                return ResourceManager.GetString("is_deletedCheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại.
        /// </summary>
        public static string is_exists {
            get {
                return ResourceManager.GetString("is_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} đã tồn tại trong cửa hàng.
        /// </summary>
        public static string is_existsInStore {
            get {
                return ResourceManager.GetString("is_existsInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trên hệ thống.
        /// </summary>
        public static string is_existsInSystem {
            get {
                return ResourceManager.GetString("is_existsInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} này đã được gắn với người dùng khác.
        /// </summary>
        public static string is_hasMapUser {
            get {
                return ResourceManager.GetString("is_hasMapUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} đã ngừng áp dụng,.
        /// </summary>
        public static string is_stopApply {
            get {
                return ResourceManager.GetString("is_stopApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} đã ngừng áp dụng, vui lòng kiểm tra lại.
        /// </summary>
        public static string is_stopApplyCheckAgain {
            get {
                return ResourceManager.GetString("is_stopApplyCheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hệ thống này đã được sử dụng bởi Nhân viên khác..
        /// </summary>
        public static string is_userHasMapEmployee {
            get {
                return ResourceManager.GetString("is_userHasMapEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thêm nhân viên mới do quá hạn mức &lt;span class=&apos;totalBasic&apos;&gt;{0} nhân viên&lt;/span&gt;.
        /// </summary>
        public static string not_allowRunningOutOfQuotaBlockEmployee {
            get {
                return ResourceManager.GetString("not_allowRunningOutOfQuotaBlockEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống.
        /// </summary>
        public static string not_empty {
            get {
                return ResourceManager.GetString("not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại.
        /// </summary>
        public static string not_exists {
            get {
                return ResourceManager.GetString("not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại trong hệ thống.
        /// </summary>
        public static string not_existsInSystem {
            get {
                return ResourceManager.GetString("not_existsInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng.
        /// </summary>
        public static string not_fomatInvalid {
            get {
                return ResourceManager.GetString("not_fomatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0}.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn ngày thiết lập làm thêm giờ.
        /// </summary>
        public static string not_haveSelectedOvertime {
            get {
                return ResourceManager.GetString("not_haveSelectedOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập hệ số lương làm thêm cho {0}.
        /// </summary>
        public static string not_haveSelectedOvertimeSalaryWithDay {
            get {
                return ResourceManager.GetString("not_haveSelectedOvertimeSalaryWithDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ.
        /// </summary>
        public static string not_invalid {
            get {
                return ResourceManager.GetString("not_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép dài quá {1} kí tự.
        /// </summary>
        public static string not_lessThan {
            get {
                return ResourceManager.GetString("not_lessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thực hiện được vì KiotViet hỗ trợ tối đa &lt;span class=&apos;totalBasic&apos;&gt;{0}&lt;/span&gt; nhân viên với &lt;span class=&apos;totalBasic&apos;&gt;gói cơ bản&lt;/span&gt;. Bạn có thể ngừng hoạt động những nhân viên không cần thiết sử dụng phần mềm hoặc sử dụng gói dịch vụ &lt;span class=&apos;totalBasic&apos;&gt;nâng cao&lt;/span&gt; của KiotViet..
        /// </summary>
        public static string not_runningOutOfQuota {
            get {
                return ResourceManager.GetString("not_runningOutOfQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng &lt;strong&gt;{0}&lt;/strong&gt; áp dụng quản lý tối đa &lt;strong&gt;{1} nhân viên&lt;/strong&gt; theo thời gian hợp đồng. Liên hệ hotline &lt;span class=&apos;totalBasic&apos;&gt;1900 6522&lt;/span&gt; để được tư vấn nâng cấp gói..
        /// </summary>
        public static string not_runningOutOfQuotaBlockEmployee {
            get {
                return ResourceManager.GetString("not_runningOutOfQuotaBlockEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có giá trị nằm giữa {1} và {2}.
        /// </summary>
        public static string number_between {
            get {
                return ResourceManager.GetString("number_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác định nhân viên.
        /// </summary>
        public static string payRate_cannotDeterminedEmployee {
            get {
                return ResourceManager.GetString("payRate_cannotDeterminedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác định chu kì làm việc.
        /// </summary>
        public static string payRate_cannotDeterminedWorkingPeriod {
            get {
                return ResourceManager.GetString("payRate_cannotDeterminedWorkingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa loại lương thành công.
        /// </summary>
        public static string payRateTemplate_deleteSuccessed {
            get {
                return ResourceManager.GetString("payRateTemplate_deleteSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên mẫu áp dụng.
        /// </summary>
        public static string payRateTemplate_emptyName {
            get {
                return ResourceManager.GetString("payRateTemplate_emptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu áp dụng {0} đã tồn tại.
        /// </summary>
        public static string payRateTemplate_existsName {
            get {
                return ResourceManager.GetString("payRateTemplate_existsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa, đang có nhân viên được áp dụng loại lương này..
        /// </summary>
        public static string payRateTemplate_notDelete {
            get {
                return ResourceManager.GetString("payRateTemplate_notDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống hỗ trợ tạo tối đa 2 bảng lương cùng lúc!.
        /// </summary>
        public static string paysheet_created_max_two_times {
            get {
                return ResourceManager.GetString("paysheet_created_max_two_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương đang trống.
        /// </summary>
        public static string paysheet_doNotHasAnyPayslip {
            get {
                return ResourceManager.GetString("paysheet_doNotHasAnyPayslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương tồn tại nhiều phiếu lương cùng một nhân viên.
        /// </summary>
        public static string paysheet_duplicateEmployee {
            get {
                return ResourceManager.GetString("paysheet_duplicateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên bảng lương.
        /// </summary>
        public static string paysheet_EmptyName {
            get {
                return ResourceManager.GetString("paysheet_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảng lương đã tồn tại trên hệ thống.
        /// </summary>
        public static string paysheet_existedCode {
            get {
                return ResourceManager.GetString("paysheet_existedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bảng lương đã có cập nhật trước đó. Bạn có muốn cập nhật lại dữ liệu không?.
        /// </summary>
        public static string paysheet_has_modifiedDate {
            get {
                return ResourceManager.GetString("paysheet_has_modifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương đang xử lỉ..
        /// </summary>
        public static string paysheet_has_pending {
            get {
                return ResourceManager.GetString("paysheet_has_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu lương {0} đã bị hủy, vui lòng kiểm tra lại.
        /// </summary>
        public static string paysheet_hasCanceledPayslip {
            get {
                return ResourceManager.GetString("paysheet_hasCanceledPayslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương đã bị hủy trước đó.
        /// </summary>
        public static string paysheet_haveBeenCancelled {
            get {
                return ResourceManager.GetString("paysheet_haveBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ làm việc tối đa trên {0} tháng.
        /// </summary>
        public static string paysheet_maximumMonths {
            get {
                return ResourceManager.GetString("paysheet_maximumMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tối đa của ngày công chuẩn là 31.
        /// </summary>
        public static string paysheet_maximumWorkingDayNumber {
            get {
                return ResourceManager.GetString("paysheet_maximumWorkingDayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian lập bảng lương không được sau thời gian phiếu thanh toán.
        /// </summary>
        public static string paysheet_minimumPayslipPaymentTime {
            get {
                return ResourceManager.GetString("paysheet_minimumPayslipPaymentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị tối thiểu của ngày công chuẩn là 1.
        /// </summary>
        public static string paysheet_minimumWorkingDayNumber {
            get {
                return ResourceManager.GetString("paysheet_minimumWorkingDayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy phiếu lương {0} thành công.
        /// </summary>
        public static string payslip_cancelSuccessfully {
            get {
                return ResourceManager.GetString("payslip_cancelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên {0} đang trùng mã phiếu lương.
        /// </summary>
        public static string payslip_duplicateCode {
            get {
                return ResourceManager.GetString("payslip_duplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phiếu lương {0} của nhân viên {1} đã tồn tại trong hệ thống..
        /// </summary>
        public static string payslip_existsCode {
            get {
                return ResourceManager.GetString("payslip_existsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu lương đã bị hủy trước đó.
        /// </summary>
        public static string payslip_haveBeenCancelled {
            get {
                return ResourceManager.GetString("payslip_haveBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật verison phiếu lương thành công.
        /// </summary>
        public static string payslip_updateVersionSuccessfully {
            get {
                return ResourceManager.GetString("payslip_updateVersionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thiết bị chấm công.
        /// </summary>
        public static string regDeviceResult {
            get {
                return ResourceManager.GetString("regDeviceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy chi tiết làm việc.
        /// </summary>
        public static string rejectWorkSchedule {
            get {
                return ResourceManager.GetString("rejectWorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ: {0}.
        /// </summary>
        public static string repeatFrom {
            get {
                return ResourceManager.GetString("repeatFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành: {0}.
        /// </summary>
        public static string repeatTo {
            get {
                return ResourceManager.GetString("repeatTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tính nửa công không hợp lệ..
        /// </summary>
        public static string setting_halfShiftMaxTimeInvalid {
            get {
                return ResourceManager.GetString("setting_halfShiftMaxTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phút tính về sớm không hợp lệ.
        /// </summary>
        public static string setting_notValidEarlyTime {
            get {
                return ResourceManager.GetString("setting_notValidEarlyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phút tính làm thêm trước ca không hợp lệ.
        /// </summary>
        public static string setting_notValidEarlyTimeOt {
            get {
                return ResourceManager.GetString("setting_notValidEarlyTimeOt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phút tính đi muộn không hợp lệ.
        /// </summary>
        public static string setting_notValidLateTime {
            get {
                return ResourceManager.GetString("setting_notValidLateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số phút tính làm thêm sau ca không hợp lệ.
        /// </summary>
        public static string setting_notValidLateTimeOt {
            get {
                return ResourceManager.GetString("setting_notValidLateTimeOt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ca tối đa ghi nhận không được nhỏ hơn 2.
        /// </summary>
        public static string setting_notValidMaxShift {
            get {
                return ResourceManager.GetString("setting_notValidMaxShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách mỗi ca cho phép không hợp lệ..
        /// </summary>
        public static string setting_notValidRangeShift {
            get {
                return ResourceManager.GetString("setting_notValidRangeShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu tính công của kỳ hạn trả lương {0} không hợp lệ.
        /// </summary>
        public static string setting_notValidStartDateWorkingPeriod {
            get {
                return ResourceManager.GetString("setting_notValidStartDateWorkingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ 1 ngày công chuẩn không hợp lệ.
        /// </summary>
        public static string setting_notValidTimeOfStandardWorkingDay {
            get {
                return ResourceManager.GetString("setting_notValidTimeOfStandardWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu tính công lần 1 và lần 2 của kỳ lương 2 lần 1 tháng không được trùng nhau.
        /// </summary>
        public static string setting_startAndEndDateTwiceAMonthEqually {
            get {
                return ResourceManager.GetString("setting_startAndEndDateTwiceAMonthEqually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa do đang có chi tiết ca làm việc thuộc ca làm việc này.
        /// </summary>
        public static string shift_cannotDelete {
            get {
                return ResourceManager.GetString("shift_cannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ làm từ không được trùng Giờ làm đến.
        /// </summary>
        public static string shift_duplicatedFromTimeToTime {
            get {
                return ResourceManager.GetString("shift_duplicatedFromTimeToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên ca.
        /// </summary>
        public static string shift_haveNotInputtedName {
            get {
                return ResourceManager.GetString("shift_haveNotInputtedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} và {2} bị trùng giờ làm việc..
        /// </summary>
        public static string shift_overlap {
            get {
                return ResourceManager.GetString("shift_overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn nhân viên.
        /// </summary>
        public static string swapShift_haveNotSelectedEmployee {
            get {
                return ResourceManager.GetString("swapShift_haveNotSelectedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn ca làm việc.
        /// </summary>
        public static string swapShift_haveNotSeletedShift {
            get {
                return ResourceManager.GetString("swapShift_haveNotSeletedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn bộ các lịch làm việc này bị trùng với {0}..
        /// </summary>
        public static string timeSheet_allDuplicated {
            get {
                return ResourceManager.GetString("timeSheet_allDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn bộ lịch làm việc không có chi tiết ca làm việc nào. Vui lòng xem lại..
        /// </summary>
        public static string timeSheet_allHaveNoClockings {
            get {
                return ResourceManager.GetString("timeSheet_allHaveNoClockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy lịch làm việc thành công.
        /// </summary>
        public static string timeSheet_cancelSuccessfully {
            get {
                return ResourceManager.GetString("timeSheet_cancelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ làm việc tối đa trên {0} ngày.
        /// </summary>
        public static string timeSheet_createPaysheetPeriodOptionDays {
            get {
                return ResourceManager.GetString("timeSheet_createPaysheetPeriodOptionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên không cùng chi nhánh với lịch làm việc.
        /// </summary>
        public static string timeSheet_differenceBetweenEmployeeBranchIdAndTSBranchId {
            get {
                return ResourceManager.GetString("timeSheet_differenceBetweenEmployeeBranchIdAndTSBranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên làm thay không cùng chi nhánh với nhân viên nghỉ.
        /// </summary>
        public static string timeSheet_differenceBetweenReplacementEmployeeBranchIdAndTSBranchId {
            get {
                return ResourceManager.GetString("timeSheet_differenceBetweenReplacementEmployeeBranchIdAndTSBranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc không cùng chi nhánh với lịch làm việc.
        /// </summary>
        public static string timeSheet_differenceBetweenShiftBranchIdAndTSBranchId {
            get {
                return ResourceManager.GetString("timeSheet_differenceBetweenShiftBranchIdAndTSBranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc bị trùng với {0}..
        /// </summary>
        public static string timeSheet_duplicated {
            get {
                return ResourceManager.GetString("timeSheet_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày nghỉ chi nhánh.
        /// </summary>
        public static string timeSheet_duplicatedBranchDayOff {
            get {
                return ResourceManager.GetString("timeSheet_duplicatedBranchDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lịch làm việc đã có khác của nhân viên.
        /// </summary>
        public static string timeSheet_duplicatedTimeSheet {
            get {
                return ResourceManager.GetString("timeSheet_duplicatedTimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên {0} đã xóa. Vui lòng kiểm tra lại.
        /// </summary>
        public static string timeSheet_employeesDoNotExist {
            get {
                return ResourceManager.GetString("timeSheet_employeesDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên được chọn không tồn tại.
        /// </summary>
        public static string timeSheet_employeesNotExist {
            get {
                return ResourceManager.GetString("timeSheet_employeesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại chi tiết ca làm việc đã chấm công không nằm trong khoảng thời gian từ Bắt đầu đến Kết thúc. Vui lòng kiểm tra lại..
        /// </summary>
        public static string timeSheet_existDataNotInRangeEndDate {
            get {
                return ResourceManager.GetString("timeSheet_existDataNotInRangeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại chi tiết ca làm việc đã chấm công không nằm trong khoảng thời gian từ Bắt đầu đến Kết thúc. Vui lòng kiểm tra lại..
        /// </summary>
        public static string timeSheet_existDataNotInRangeStartDate {
            get {
                return ResourceManager.GetString("timeSheet_existDataNotInRangeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập chấm công trên thiết bị di dộng:{0}.
        /// </summary>
        public static string timeSheet_gps_audit_updateSetting_subTitle_1 {
            get {
                return ResourceManager.GetString("timeSheet_gps_audit_updateSetting_subTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thiết lập tính năng:{0}.
        /// </summary>
        public static string timeSheet_gps_audit_updateSetting_title {
            get {
                return ResourceManager.GetString("timeSheet_gps_audit_updateSetting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin Gps cho chi nhánh {0} đã tồn tại.
        /// </summary>
        public static string timeSheet_gpsInfoHasExits {
            get {
                return ResourceManager.GetString("timeSheet_gpsInfoHasExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc phải lớn hơn Ngày bắt đầu.
        /// </summary>
        public static string timeSheet_greaterStartDateEndDate {
            get {
                return ResourceManager.GetString("timeSheet_greaterStartDateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc đã bị hủy trước đó. Vui lòng kiểm tra lại.
        /// </summary>
        public static string timeSheet_haveBeenCancelled {
            get {
                return ResourceManager.GetString("timeSheet_haveBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc không có chi tiết ca làm việc nào. Vui lòng xem lại..
        /// </summary>
        public static string timeSheet_haveNoClockings {
            get {
                return ResourceManager.GetString("timeSheet_haveNoClockings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc không được nhỏ hơn Ngày bắt đầu.
        /// </summary>
        public static string timeSheet_lessthanStartDateEndDate {
            get {
                return ResourceManager.GetString("timeSheet_lessthanStartDateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được đặt lịch quá {0} tháng..
        /// </summary>
        public static string timeSheet_maximumBookCalendar {
            get {
                return ResourceManager.GetString("timeSheet_maximumBookCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhân viên không được vượt quá 100.
        /// </summary>
        public static string timeSheet_maximumSelectedEmployee {
            get {
                return ResourceManager.GetString("timeSheet_maximumSelectedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng lịch làm việc cần cập nhật không được quá {0}.
        /// </summary>
        public static string timeSheet_maximumSelectedTimeSheet {
            get {
                return ResourceManager.GetString("timeSheet_maximumSelectedTimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian sao chép tối đa 31 ngày.
        /// </summary>
        public static string timeSheet_maxTimeCopy {
            get {
                return ResourceManager.GetString("timeSheet_maxTimeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có lịch làm việc nào nằm trong khoảng thời gian chọn để sao chép.
        /// </summary>
        public static string timeSheet_noDataInRangeTimeSelectForCopy {
            get {
                return ResourceManager.GetString("timeSheet_noDataInRangeTimeSelectForCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc đã bị hủy. Vui lòng kiểm tra lại.
        /// </summary>
        public static string timeSheet_notExist {
            get {
                return ResourceManager.GetString("timeSheet_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn bộ các lịch làm việc này bị trùng với lịch làm việc đã có khác của nhân viên.
        /// </summary>
        public static string timeSheet_noTimeSheetIsCreated {
            get {
                return ResourceManager.GetString("timeSheet_noTimeSheetIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã xóa. Vui lòng kiểm tra lại.
        /// </summary>
        public static string timeSheet_objectsDoNotExist {
            get {
                return ResourceManager.GetString("timeSheet_objectsDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã ngừng hoạt động. Vui lòng kiểm tra lại.
        /// </summary>
        public static string timeSheet_objectsInactive {
            get {
                return ResourceManager.GetString("timeSheet_objectsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên làm thay đã bị xóa.
        /// </summary>
        public static string timeSheet_replacementEmployeeDoesNotExist {
            get {
                return ResourceManager.GetString("timeSheet_replacementEmployeeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} thành công.
        /// </summary>
        public static string update_successed {
            get {
                return ResourceManager.GetString("update_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật {0} lịch làm việc thuộc ca {1}.
        /// </summary>
        public static string updateClockingTime {
            get {
                return ResourceManager.GetString("updateClockingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhân viên.
        /// </summary>
        public static string updateEmployee {
            get {
                return ResourceManager.GetString("updateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thiết lập tính năng.
        /// </summary>
        public static string updateSettingInfo {
            get {
                return ResourceManager.GetString("updateSettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá mẫu áp dụng vì mẫu áp dụng hiện vẫn còn được sử dụng cho nhân viên trong cửa hàng. Vui lòng bỏ mẫu áp dụng cho nhân viên trước khi xoá..
        /// </summary>
        public static string validate_when_del_payrateTpl {
            get {
                return ResourceManager.GetString("validate_when_del_payrateTpl", resourceCulture);
            }
        }
    }
}
