// <auto-generated />
using System;
using KiotVietTimeSheet.Infrastructure.EventBus.EventLog.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace KiotVietTimeSheet.Api.Migrations.EfTimeSheetIntegrationEventLogContext
{
    [DbContext(typeof(EfIntegrationEventLogContext))]
    [Migration("20191025043251_InitIntegrationLog")]
    partial class InitIntegrationLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KiotVietTimeSheet.Infrastructure.EventBus.Models.IntegrationEventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<DateTime?>("ProcessedTime");

                    b.Property<int>("State");

                    b.Property<int>("TimeSent");

                    b.Property<Guid>("TransactionId");

                    b.HasKey("EventId");

                    b.HasIndex("State")
                        .HasName("NonClusteredIndex-IntegrationEventLogEntry-State");

                    b.ToTable("IntegrationEventLogEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
